server:
  port: 7003

#Eureka配置
eureka:
  instance:
    hostname: localhost3 #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向Eureka注册中心注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url:
      defaultZone: http://localhost1:7001/eureka/,http://localhost2:7002/eureka/


