server:
  port: 9527

#spring配置
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id:  zuul-9527.com
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId:  springcloud-provider-dept
    mydept.path:  /mydept/**
  #ignored-services: springcloud-provider-dept #不能在使用这个路径访问
  ignored-services: "*" #隐藏全部的
  #prefix: /kuang #增加公共的前缀

info:
  app.name: springcloud-zuul
  version: 1.0

